"use client";

import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { useTheme } from "next-themes";
import { TextAnimate } from "@/components/magicui/text-animate";
import { PixelImage } from "@/components/magicui/pixel-image";
import { HyperText } from "@/components/magicui/hyper-text";
import { Highlighter } from "@/components/magicui/highlighter";
import GithubGrid from "./GithubGrid";

export default function Hero() {
    const { theme } = useTheme();
    const [mounted, setMounted] = useState(false);
    const [highlightsTrigger, setHighlightsTrigger] = useState(false);

    const [textIndex, setTextIndex] = useState(0);

    useEffect(() => {
        setMounted(true);
        const t = setTimeout(() => {
            setHighlightsTrigger(true);
        }, 1500);
        return () => clearTimeout(t);
    }, []);

    useEffect(() => {
        if (!mounted) return;
        const interval = setInterval(() => {
            setTextIndex((prev) => (prev + 1) % snarkyTexts.length);
        }, 3500);
        return () => clearInterval(interval);
    }, [mounted]);

    const snarkyTexts = [
        "Trying hard to make this portfolio better.",
        "Tuning LLMs to make them go absolutely bonkers.",
        "Breaking production so you don't have to.",
        "Prompt engineering my way out of actual coding.",
        "Refactoring the same component for the 4th time.",
        "Convincing AI that it's actually sentient.",
        "Deleting code and calling it 'optimization'."
    ];

    const isDark = mounted && theme === "dark";

    const copyAIContent = `
# Divax Shah - AI/ML Engineer & Founder
Building premium-grade AI systems, commercial SaaS products, and fine-tuning specialized LLMs/VLMs.

## PROFESSIONAL EXPERIENCE
- **Solo Founder @ Rented Souls (2025 - Present)**: Built and scaled an enterprise AI digital persona platform utilizing advanced video generation (WAN 2.5 I2V, Seedream, Nano Banana) and TTS architectures (Kokoro).
- **Co-Founder & Architect @ Your Humanizer (2025 - Present)**: Built a universal AI text transformation SaaS handling prompt routing for text generated by GPT-4.5, Claude 3.5, and Gemini to enhance natural readability.
- **AI/ML Engineer @ Avinyaa Edtech (2025 - Present)**: Developing AI Writing Tools, grammar checkers, and text detection systems via Transformer/LLM fine-tuning.
- **Jr. Python Developer @ Thinkbiz Tech (2024 - 2025)**: Built scalable chatbot PoCs and created 'Jugaad', an OCR-LLM pipeline improving invoice parsing accuracy.
- **AI & Synth Data Intern @ DMI Finance (2024)**: Created generative pipelines for synthetic structured data via Gradio & PyTorch.

## CORE PROJECTS
- **SANSKRIT QWEN2.5-7B TRANSLATE V2**: Highly optimized bidirectional Sanskrit translation model trained via LoRA using flash attention.
- **SANSKRIT QWEN2.5-VL OCR**: Vision-Language model adapted for Sanskrit OCR tasks.
- **OPEN-LLAMA-3.2-1B-INSTRUCT**: Instruct-tuned LLaMA 3.2 1B on OpenHermes using Axolotl and DeepSpeed.
- **ION-LLM-BASE**: 100M parameter GPT-style Transformer built from scratch on Fineweb via DeepSpeed ZeRO-2.
- **GITAWHISPER**: Fine-tuned Whisper-tiny for Sanskrit shloka transcription with IAST transliteration.
- **LORE KEEPER**: Infinite structural narrative AI generator using custom LLM agents.
- **WORLD SIM**: CLI-native dynamic sandbox environment simulator.
- **FLUX LORA ECOSYSTEM**: Specialized generative AI adapters fine-tuned on diverse image datasets.

## SKILLS & ARTIFACTS
- **PROGRAMMING LANGUAGES**: Python
- **FRAMEWORKS & LIBRARIES**: PyTorch, TensorFlow / Keras, scikit-learn, Hugging Face Transformers, LangChain, NumPy, Pandas, Fastapi, AWS, DeepSpeed
- **AI DOMAINS**: Generative AI, Large Language Model (LLM/VLLM) Fine-Tuning, Reinforcement Learning (RL), Natural Language Processing (NLP), Prompt Engineering, Axolotl AI, Unsloth AI
- **APIs & SERVICES**: OpenAI, Google Gemini, Anthropic, Mistral AI, Groq, OpenRouter

## CONTACT
- Email: divax12345@gmail.com
- GitHub: shahdivax
- Hugging Face: diabolic6045
`;

    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(copyAIContent);
            alert("Copied to clipboard for AI");
        } catch (err) {
            console.error("Failed to copy text: ", err);
        }
    };

    if (!mounted) return null;

    // Minimalistic variables
    const boxBg = isDark ? "bg-[#0a0a0a]" : "bg-white";
    const boxBorder = isDark ? "border-[#404040]" : "border-gray-300";
    const accentText = isDark ? "text-[#ea580c]" : "text-[#2563eb]";
    const accentBg = isDark ? "bg-[#ea580c]/20" : "bg-[#2563eb]/20";
    const highlightColor = isDark ? "#ea580c33" : "#2563eb33"; // 20% opacity equivalent

    return (
        <section className="w-full grid grid-cols-1 xl:grid-cols-[1fr_minmax(auto,1000px)_1fr] border-b border-[var(--border)] relative z-10 bg-transparent pt-14">
            {/* Left Blueprint Gutter */}
            <div className="hidden xl:block border-r border-[var(--border)]" />

            {/* Core 1000px Grid Zone */}
            <div className="w-full grid grid-cols-12 gap-0 border-x xl:border-x-0 border-[var(--border)] bg-[var(--background)]">
                
                {/* 1. Profile Image Box */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: "easeOut" }}
                    className={`col-span-4 md:col-span-4 lg:col-span-3 aspect-square relative border-b border-r border-[var(--border)] p-2 sm:p-4 overflow-hidden flex items-center justify-center`}
                >
                    <div className="w-full h-full relative bg-black/5 group/portrait">
                        <PixelImage
                            src="https://res.cloudinary.com/djc2l2zjr/image/upload/v1771571110/1771570920892_2_l2drnn.jpg"
                            customGrid={{ rows: 8, cols: 8 }}
                            grayscaleAnimation
                            className={`w-full h-full object-cover transition-all duration-700
                                scale-105 group-hover/portrait:scale-100
                                ${isDark
                                    ? "brightness-90 group-hover/portrait:brightness-100"
                                    : "group-hover/portrait:brightness-105"
                                }`}
                        />
                    </div>
                </motion.div>

                {/* 2. Main Title Box */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: "easeOut", delay: 0.1 }}
                    className={`col-span-8 md:col-span-8 lg:col-span-9 border-b border-[var(--border)] p-4 sm:p-8 md:p-12 flex flex-col justify-center relative bg-[var(--background)]`}
                >
                    <h1 className="text-2xl sm:text-5xl md:text-6xl lg:text-7xl font-bold tracking-tighter uppercase mb-1 sm:mb-2 font-[family-name:var(--font-syne)] leading-[0.9]">
                        <TextAnimate animation="blurInUp" by="character" duration={1}>
                            DIVAX SHAH
                        </TextAnimate>
                    </h1>
                    <div className="flex flex-col gap-1 sm:gap-2 mt-2 sm:mt-4 h-6 relative w-full">
                        <AnimatePresence mode="popLayout">
                            <motion.div
                                key={textIndex}
                                exit={{ y: -10, opacity: 0, filter: "blur(4px)" }}
                                transition={{ duration: 0.4, ease: "easeOut" }}
                                className={`font-mono text-[8px] sm:text-[10px] md:text-xs tracking-widest uppercase absolute w-full ${accentText}`}
                            >
                                <TextAnimate animation="blurInUp" by="character" once>
                                    {snarkyTexts[textIndex]}
                                </TextAnimate>
                            </motion.div>
                        </AnimatePresence>
                    </div>
                </motion.div>

                {/* 3. Bio Box */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: "easeOut", delay: 0.2 }}
                    className={`col-span-12 md:col-span-8 lg:col-span-8 border-b md:border-b-0 md:border-r border-[var(--border)] p-6 sm:p-10 relative bg-[var(--background)]`}
                >
                    <div className={`font-mono text-xs sm:text-sm leading-relaxed ${isDark ? "text-zinc-400" : "text-zinc-600"}`}>
                        Building and fine-tuning{" "}
                        <Highlighter action="highlight" color={highlightColor} isView={true} trigger={highlightsTrigger} padding={4} multiline={true}>
                            <span className={`font-bold ${accentText}`}>
                                <HyperText as="span" className="inline" duration={600}>LLMs and VLMs</HyperText>
                            </span>
                        </Highlighter>
                        , with experience adapting models for specific tasks such as{" "}
                        <Highlighter action="highlight" color={highlightColor} isView={true} trigger={highlightsTrigger} padding={4} multiline={true}>
                            <span className={`font-bold ${accentText}`}>
                                <HyperText as="span" className="inline" duration={600}>Sanskrit translation</HyperText>
                            </span>
                        </Highlighter>
                        {" "}and transliteration, a{" "}
                        <Highlighter action="highlight" color={highlightColor} isView={true} trigger={highlightsTrigger} padding={4} multiline={true}>
                            <span className={`font-bold ${accentText}`}>
                                <HyperText as="span" className="inline" duration={600}>Sanskrit VLM-OCR</HyperText>
                            </span>
                        </Highlighter>
                        {" "}model, a Whisper-based ASR model with{" "}
                        <Highlighter action="highlight" color={highlightColor} isView={true} trigger={highlightsTrigger} padding={4} multiline={true}>
                            <span className={`font-bold ${accentText}`}>
                                <HyperText as="span" className="inline" duration={600}>35% lower error rate</HyperText>
                            </span>
                        </Highlighter>
                        , and a tokenizer that improved efficiency by{" "}
                        <Highlighter action="highlight" color={highlightColor} isView={true} trigger={highlightsTrigger} padding={4} multiline={true}>
                            <span className={`font-bold ${accentText}`}>
                                <HyperText as="span" className="inline" duration={600}>4.5×</HyperText>
                            </span>
                        </Highlighter>.
                    </div>
                </motion.div>

                {/* 4. Actions Box */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: "easeOut", delay: 0.3 }}
                    className={`col-span-12 md:col-span-4 lg:col-span-4 border-b md:border-b-0 border-[var(--border)] p-6 flex flex-col justify-center gap-3 bg-[var(--background)]`}
                >
                    <a
                        href="https://huggingface.co/datasets/diabolic6045/divax-portfolio/resolve/main/public/resume.pdf"
                        target="_blank"
                        rel="noreferrer"
                        className={`w-full text-center px-4 py-4 text-[10px] font-mono font-bold tracking-[0.2em] uppercase transition-all duration-300 ${accentBg} ${accentText} hover:brightness-125 border border-transparent`}
                    >
                        DOWNLOAD RESUME
                    </a>
                    <button
                        onClick={handleCopy}
                        className={`w-full text-center px-4 py-4 text-[10px] font-mono font-bold tracking-[0.2em] uppercase transition-all duration-300 border border-[var(--border)] ${isDark ? "hover:bg-white hover:text-black" : "hover:bg-black hover:text-white"}`}
                    >
                        COPY FOR AI
                    </button>
                    <div className="grid grid-cols-2 gap-3">
                        <a
                            href="https://github.com/shahdivax"
                            target="_blank"
                            rel="noreferrer"
                            className={`w-full text-center px-3 py-3 text-[9px] font-mono font-bold tracking-[0.2em] uppercase transition-all duration-300 border border-[var(--border)] ${isDark ? "hover:bg-white hover:text-black" : "hover:bg-black hover:text-white"}`}
                        >
                            GITHUB ↗
                        </a>
                        <a
                            href="https://huggingface.co/diabolic6045"
                            target="_blank"
                            rel="noreferrer"
                            className={`w-full text-center px-3 py-3 text-[9px] font-mono font-bold tracking-[0.2em] uppercase transition-all duration-300 border border-[var(--border)] ${isDark ? "hover:bg-white hover:text-black" : "hover:bg-black hover:text-white"}`}
                        >
                            HF ↗
                        </a>
                    </div>
                </motion.div>

                {/* 5. GitHub Graph Box */}
                <motion.div 
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: "easeOut", delay: 0.4 }}
                    className={`col-span-12 border-t border-[var(--border)] p-6 sm:p-10 flex flex-col justify-center relative bg-[var(--background)]`}
                >
                    <GithubGrid />
                </motion.div>

            </div>

            {/* Right Blueprint Gutter */}
            <div className="hidden xl:block border-l border-[var(--border)]" />
        </section>
    );
}
